Add "make format" and "make format-check" to check format for c/c++ files

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -19,6 +19,22 @@
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
+if ! hash astyle; then
+	echo "You do not have astyle installed so your code style is not being checked!"
+	exit 0
+fi
+
+info=$(make format-check)
+if [ -n "$info" ]; then
+	echo "Format Error detected:"
+	echo
+	echo "$info"
+	echo
+	echo "Please run \`make format\` before next commit."
+	echo
+	exit 1
+fi
+
 cd src/libos
 output=$(cargo fmt -- --check 2>&1)
 retval=$?
diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,4 +4,8 @@ services:
   - docker
 
 script:
-- docker run -v /home/travis/build/occlum/occlum:/root/occlum occlum/occlum:0.12.0-ubuntu18.04 /bin/bash -c "cd /root/occlum; make submodule; SGX_MODE=SIM make; SGX_MODE=SIM make test"
+- docker run -v /home/travis/build/occlum/occlum:/root/occlum occlum/occlum:0.12.0-ubuntu18.04 /bin/bash -c "cd /root/occlum; \
+                info=$(make format-check); \
+                if [ -n "$info" ]; then echo "Format error detected."; exit 1; \
+                fi; \
+                make submodule; SGX_MODE=SIM make; SGX_MODE=SIM make test"
