Add helper command to print mrsigner, mrenclave and conf_mac

diff --git a/tools/occlum b/tools/occlum
--- a/tools/occlum
+++ b/tools/occlum
@@ -85,6 +85,10 @@ Usage:
 
     occlum gen-image-key <key_path>
         Generate a file consists of a randomly generated 128-bit key for encryption of the FS image.
+
+    occlum print mrsigner|mrenclave|conf_mac
+        Print Occlum instance's mrsigner, mrenclave or file system's (actually it is the configuration file
+        of init fs + root fs) 128bits MAC.
 EOF
 }
 
@@ -580,6 +584,35 @@ cmd_gen_image_key() {
     cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1 | sed -r 's/.{2}/&-/g; s/.$//' > $key_path
 }
 
+cmd_print_info() {
+    if [ -z $1 ]; then
+        echo "Error: print info name not provided"
+        exit 1
+    fi
+
+    libos_so="build/lib/libocclum-libos.signed.so"
+    info="$1"
+
+    [ -e "$libos_so" ] || \
+        exit_error "No $libos_so existed"
+
+    if [[ "$info" == "mrenclave" ]]; then
+        sgx_sign dump -enclave $libos_so -dumpfile dumpfile >/dev/null 2>&1
+        sed -n -e '/enclave_hash.m/,/metadata->enclave_css.body.isv_prod_id/p' dumpfile \
+            |head -3|tail -2|xargs|sed 's/0x//g'|sed 's/ //g'
+        rm dumpfile
+    elif [[ "$info" == "mrsigner" ]]; then
+        sgx_sign dump -enclave $libos_so -dumpfile dumpfile >/dev/null 2>&1
+        tail -2 dumpfile |xargs|sed 's/0x//g'|sed 's/ //g'
+        rm dumpfile
+    elif [[ "$info" == "conf_mac" ]]; then
+        LD_LIBRARY_PATH="$SGX_SDK/sdk_libs" \
+		"$occlum_dir/build/bin/occlum-protect-integrity" show-mac "./build/.Occlum_sys.json.protected"
+    else
+        exit_error "No valid info name provided"
+    fi
+}
+
 set -e
 
 if [[ ( "$#" < 1 ) ]] ; then
@@ -624,6 +657,9 @@ case "$cmd" in
         ;;
     gen-image-key)
         cmd_gen_image_key "${@:2:1}"
+        ;;
+    print)
+        cmd_print_info "${@:2:1}"
         ;;
     *)
         report_arg_error "Error: unknown sub-command $cmd"
