[ci] Remove CentOS tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,38 +43,38 @@ jobs:
       if: ${{ failure() }}
       run: docker exec ${{ github.job }} bash -c "cat /root/occlum/build/test/.fail"
 
-  Make_test_on_centos:
-    runs-on: ubuntu-20.04
+  # Make_test_on_centos:
+  #   runs-on: ubuntu-20.04
 
-    steps:
-    - uses: actions/checkout@v1
-      with:
-        submodules: true
+  #   steps:
+  #   - uses: actions/checkout@v1
+  #     with:
+  #       submodules: true
 
-    - uses: ./.github/workflows/composite_action/sim
-      with:
-        container-name: ${{ github.job }}
-        build-envs: 'OCCLUM_RELEASE_BUILD=1'
-        os: 'centos8.2'
-        container-flags: '--privileged'
+  #   - uses: ./.github/workflows/composite_action/sim
+  #     with:
+  #       container-name: ${{ github.job }}
+  #       build-envs: 'OCCLUM_RELEASE_BUILD=1'
+  #       os: 'centos8.2'
+  #       container-flags: '--privileged'
 
-    - name: Check format
-      run:  docker exec ${{ github.job }} bash -c 'cd /root/occlum; info=$(make format-check);
-        if [[ -n $info ]]; then
-          echo "Format error detected.";
-          echo "$info";
-          exit 1;
-        fi'
+  #   - name: Check format
+  #     run:  docker exec ${{ github.job }} bash -c 'cd /root/occlum; info=$(make format-check);
+  #       if [[ -n $info ]]; then
+  #         echo "Format error detected.";
+  #         echo "$info";
+  #         exit 1;
+  #       fi'
 
-    - name: Unit test
-      run: docker exec ${{ github.job }} bash -c "cd /root/occlum; make unit-test"
+  #   - name: Unit test
+  #     run: docker exec ${{ github.job }} bash -c "cd /root/occlum; make unit-test"
 
-    - name: Integration test
-      run:  docker exec ${{ github.job }} bash -c "cd /root/occlum; OCCLUM_LOG_LEVEL=trace SGX_MODE=SIM make test"
+  #   - name: Integration test
+  #     run:  docker exec ${{ github.job }} bash -c "cd /root/occlum; OCCLUM_LOG_LEVEL=trace SGX_MODE=SIM make test"
 
-    - name: Integration test with Glibc
-      run:  docker exec ${{ github.job }} bash -c "cd /root/occlum; OCCLUM_LOG_LEVEL=trace SGX_MODE=SIM make test-glibc"
+  #   - name: Integration test with Glibc
+  #     run:  docker exec ${{ github.job }} bash -c "cd /root/occlum; OCCLUM_LOG_LEVEL=trace SGX_MODE=SIM make test-glibc"
 
-    - name: Show failed cases
-      if: ${{ failure() }}
-      run: docker exec ${{ github.job }} bash -c "cat /root/occlum/build/test/.fail"
+  #   - name: Show failed cases
+  #     if: ${{ failure() }}
+  #     run: docker exec ${{ github.job }} bash -c "cat /root/occlum/build/test/.fail"
